<<<<<<<< HEAD:src/IotRestApi/Measurements/measurements-tests.http
@Startup_HostAddress = http://localhost:5141/api/iot
========
@Startup_HostAddress = http://localhost:5105/iot

GET {{Startup_HostAddress}}/hello/
#Accept: application/json

###
>>>>>>>> main:src/IotRestApi/Measurements/MeasurementsEndpoints.http

GET {{Startup_HostAddress}}/measure/
Accept: application/json

###

POST {{Startup_HostAddress}}/measure/
Content-Type:  application/json
{
  "deviceId": 10,
  "measurements": [
    {
      "sensorId": 8,
      "value": 12.4
    }
  ]
}

###
