@Startup_HostAddress = http://localhost:5141/api/iot

GET {{Startup_HostAddress}}/measure/
Accept: application/json

###

POST {{Startup_HostAddress}}/measure/
Content-Type:  application/json
{
  "deviceId": 10,
  "measurements": [
    {
      "sensorId": 8,
      "value": 12.4
    }
  ]
}

###
