// <auto-generated />
using System;
using DevTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevTest.Migrations
{
    [DbContext(typeof(TestingContext))]
    [Migration("20240803194846_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DevTest.DeviceV5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DevTest.MeasureV5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorV5Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SensorV5Id");

                    b.ToTable("Measure");

                    b.HasDiscriminator().HasValue("MeasureV5");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DevTest.SensorV5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceV5Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceV5Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("DevTest.MeasurePercentageV5", b =>
                {
                    b.HasBaseType("DevTest.MeasureV5");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("Measure", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("MeasurePercentageV5_Value");
                        });

                    b.HasDiscriminator().HasValue("MeasurePercentageV5");
                });

            modelBuilder.Entity("DevTest.MeasureTemperatureV5", b =>
                {
                    b.HasBaseType("DevTest.MeasureV5");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("MeasureTemperatureV5");
                });

            modelBuilder.Entity("DevTest.MeasureV5", b =>
                {
                    b.HasOne("DevTest.SensorV5", "SensorV5")
                        .WithMany("Measures")
                        .HasForeignKey("SensorV5Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorV5");
                });

            modelBuilder.Entity("DevTest.SensorV5", b =>
                {
                    b.HasOne("DevTest.DeviceV5", "DeviceV5")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceV5Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceV5");
                });

            modelBuilder.Entity("DevTest.DeviceV5", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("DevTest.SensorV5", b =>
                {
                    b.Navigation("Measures");
                });
#pragma warning restore 612, 618
        }
    }
}
