@AuthApp.Server_HostAddress_Public = http://localhost:5162/api/web/public
@AuthApp.Server_HostAddress_Protected = http://localhost:5162/api/web/protected

POST {{AuthApp.Server_HostAddress_Public}}/auth/register
Content-Type: application/json

{
  "email": "admin1@admin.Com",
  "password": "admin1@admin.Com"
}

###

POST {{AuthApp.Server_HostAddress_Public}}/auth/login?useCookies=true
Access-Control-Allow-Credentials: true
Content-Type: application/json

{
  "email": "admin1@admin.Com",
  "password": "admin1@admin.Com"
}

###

GET {{AuthApp.Server_HostAddress_Protected}}/weatherforecast
Access-Control-Allow-Credentials: true
Accept: application/json

###

# For more info on HTTP files go to https://aka.ms/vs/httpfile
