@WebApp.Server_HostAddress = http://localhost:5162/api/web

GET {{WebApp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

# For more info on HTTP files go to https://aka.ms/vs/httpfile