<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="WebApp\**" />
    <EmbeddedResource Remove="WebApp\**" />
    <None Remove="WebApp\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server.Domain\Server.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNext" Version="5.14.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
